const CREATE_BOUNTY                    = 'dml/bounties/CREATE_BOUNTY';
const CREATE_BOUNTY_ERROR              = 'dml/bounties/CREATE_BOUNTY_ERROR';
const CREATE_BOUNTY_SUCCESS            = 'dml/bounties/CREATE_BOUNTY_SUCCESS';
const CREATE_BOUNTY_ENROLLMENT         = 'dml/bounties/CREATE_BOUNTY_ENROLLMENT';
const CREATE_BOUNTY_ENROLLMENT_ERROR   = 'dml/bounties/CREATE_BOUNTY_ENROLLMENT_ERROR';
const CREATE_BOUNTY_ENROLLMENT_SUCCESS = 'dml/bounties/CREATE_BOUNTY_ENROLLMENT_SUCCESS';
const LIST_BOUNTIES                    = 'dml/bounties/LIST_BOUNTIES';
const LIST_BOUNTIES_ERROR              = 'dml/bounties/LIST_BOUNTIES_ERROR';
const LIST_BOUNTIES_MINE               = 'dml/bounties/LIST_BOUNTIES_MINE';
const LIST_BOUNTIES_MINE_ERROR         = 'dml/bounties/LIST_BOUNTIES_MINE_ERROR';
const LIST_BOUNTY_ENROLLMENTS          = 'dml/bounties/LIST_BOUNTY_ENROLLMENTS';
const LIST_BOUNTY_ENROLLMENTS_ERROR    = 'dml/bounties/LIST_BOUNTY_ENROLLMENTS_ERROR';
const OPEN_BOUNTY                      = 'dml/bounties/OPEN_BOUNTY';
const OPEN_BOUNTY_ERROR                = 'dml/bounties/OPEN_BOUNTY_ERROR';
const OPEN_BOUNTY_SUCCESS              = 'dml/bounties/OPEN_BOUNTY_SUCCESS';
const SHOW_BOUNTY                      = 'dml/bounties/SHOW_BOUNTY';
const SHOW_BOUNTY_ERROR                = 'dml/bounties/SHOW_BOUNTY_ERROR';
const UPDATE_BOUNTY                    = 'dml/bounties/UPDATE_BOUNTY';
const UPDATE_BOUNTY_ERROR              = 'dml/bounties/UPDATE_BOUNTY_ERROR';
const UPDATE_BOUNTY_SUCCESS            = 'dml/bounties/UPDATE_BOUNTY_SUCCESS';

export default {
  CREATE_BOUNTY,
  CREATE_BOUNTY_ERROR,
  CREATE_BOUNTY_SUCCESS,
  CREATE_BOUNTY_ENROLLMENT,
  CREATE_BOUNTY_ENROLLMENT_ERROR,
  CREATE_BOUNTY_ENROLLMENT_SUCCESS,
  LIST_BOUNTIES,
  LIST_BOUNTIES_ERROR,
  LIST_BOUNTIES_MINE,
  LIST_BOUNTIES_MINE_ERROR,
  LIST_BOUNTY_ENROLLMENTS,
  LIST_BOUNTY_ENROLLMENTS_ERROR,
  OPEN_BOUNTY,
  OPEN_BOUNTY_ERROR,
  OPEN_BOUNTY_SUCCESS,
  SHOW_BOUNTY,
  SHOW_BOUNTY_ERROR,
  UPDATE_BOUNTY,
  UPDATE_BOUNTY_ERROR,
  UPDATE_BOUNTY_SUCCESS,
};
