const HYDRATE_USER_DATA         = 'dml/account/HYDRATE_USER_DATA';
const HYDRATE_USER_DATA_ERROR   = 'dml/account/HYDRATE_USER_DATA_ERROR';
const HYDRATE_USER_DATA_SUCCESS = 'dml/account/HYDRATE_USER_DATA_SUCCESS';
const LIST_USERS                = 'dml/account/LIST_USERS';
const LIST_USERS_ERROR          = 'dml/account/LIST_USERS_ERROR';
const LOAD_ACCOUNT_DATA         = 'dml/account/LOAD_ACCOUNT_DATA';
const UPDATE_USER               = 'dml/account/UPDATE_USER';
const UPDATE_USER_ERROR         = 'dml/account/UPDATE_USER_ERROR';
const UPDATE_USER_SUCCESS       = 'dml/account/UPDATE_USER_SUCCESS';

export default {
  HYDRATE_USER_DATA,
  HYDRATE_USER_DATA_ERROR,
  HYDRATE_USER_DATA_SUCCESS,
  LIST_USERS_ERROR,
  LIST_USERS,
  LOAD_ACCOUNT_DATA,
  UPDATE_USER_ERROR,
  UPDATE_USER_SUCCESS,
  UPDATE_USER,
};
