const CREATE_ALGORITHM           = 'dml/algorithms/CREATE_ALGORITHM';
const CREATE_ALGORITHM_ERROR     = 'dml/algorithms/CREATE_ALGORITHM_ERROR';
const CREATE_ALGORITHM_SUCCESS   = 'dml/algorithms/CREATE_ALGORITHM_SUCCESS';
const DOWNLOAD_ALGORITHM         = 'dml/algorithms/DOWNLOAD_ALGORITHM';
const DOWNLOAD_ALGORITHM_ERROR   = 'dml/algorithms/DOWNLOAD_ALGORITHM_ERROR';
const DOWNLOAD_ALGORITHM_SUCCESS = 'dml/algorithms/DOWNLOAD_ALGORITHM_SUCCESS';
const LIST_ALGORITHMS            = 'dml/algorithms/LIST_ALGORITHMS';
const LIST_ALGORITHMS_ERROR      = 'dml/algorithms/LIST_ALGORITHMS_ERROR';
const LIST_ALGORITHMS_MINE       = 'dml/algorithms/LIST_ALGORITHMS_MINE';
const LIST_ALGORITHMS_MINE_ERROR = 'dml/algorithms/LIST_ALGORITHMS_MINE_ERROR';
const SHOW_ALGORITHM             = 'dml/algorithms/SHOW_ALGORITHM';
const SHOW_ALGORITHM_ERROR       = 'dml/algorithms/SHOW_ALGORITHM_ERROR';
const UPDATE_ALGORITHM           = 'dml/algorithms/UPDATE_ALGORITHM';
const UPDATE_ALGORITHM_ERROR     = 'dml/algorithms/UPDATE_ALGORITHM_ERROR';
const UPDATE_ALGORITHM_SUCCESS   = 'dml/algorithms/UPDATE_ALGORITHM_SUCCESS';

export default {
  CREATE_ALGORITHM,
  CREATE_ALGORITHM_ERROR,
  CREATE_ALGORITHM_SUCCESS,
  DOWNLOAD_ALGORITHM,
  DOWNLOAD_ALGORITHM_ERROR,
  DOWNLOAD_ALGORITHM_SUCCESS,
  LIST_ALGORITHMS,
  LIST_ALGORITHMS_ERROR,
  LIST_ALGORITHMS_MINE,
  LIST_ALGORITHMS_MINE_ERROR,
  SHOW_ALGORITHM,
  SHOW_ALGORITHM_ERROR,
  UPDATE_ALGORITHM,
  UPDATE_ALGORITHM_ERROR,
  UPDATE_ALGORITHM_SUCCESS,
};
