const SELECT_CATEGORY = "dml/marketplace/SELECT_CATEGORY";
const SELECT_TAG = "dml/marketplace/SELECT_TAG";
const FILTER_ALGORITHMS = "dml/marketplace/FILTER_ALGORITHMS";
const DESELECT_CATEGORY = "dml/marketplace/DESELECT_CATEGORY";
const DESELECT_TAG = "dml/marketplace/DESELECT_TAG";
const START_LOADING_ALGORITHMS = "dml/marketplace/START_LOADING_ALGORITHMS";
const FINISH_LOADING_ALGORITHMS = "dml/marketplace/FINISH_LOADING_ALGORITHMS";
const UPLOAD_IMAGE = "dml/marketplace/UPLOAD_IMAGE";

export default {
  SELECT_CATEGORY,
  DESELECT_CATEGORY,
  FILTER_ALGORITHMS,
  SELECT_TAG,
  DESELECT_TAG,
  START_LOADING_ALGORITHMS,
  FINISH_LOADING_ALGORITHMS,
  UPLOAD_IMAGE
};
